version: '3.2'

services:

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: Polkadot CC1
        NETWORK_ID: polkadot-cc1
        NETWORK_TYPE: pre
        CHAIN_TYPE: relay
        NETWORK_TOKEN_SYMBOL: DOT
        NETWORK_TOKEN_DECIMALS: 12
        NETWORK_COLOR_CODE: e6007a
        NGINX_CONF: nginx/polkascan-gui.conf
        API_URL: https://api-01.polkascan.io/polkadot/api/v1
    ports:
      - '8080:80'

  polkadot-ui:
    image: polkasource/substrate-ui:polkadot-latest
    ports:
      - '8081:80'
