version: '3.2'

services:

  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://substrate-node:9933/
      - SUBSTRATE_METADATA_VERSION=4
    depends_on:
      - mysql
      - substrate-node

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://substrate-node:9933/
    depends_on:
      - redis
      - mysql
      - substrate-node

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis
      - mysql

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    ports:
      - '5555:5555'
    command:  flower -A app.tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:latest
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

  substrate-node:
    image: polkasource/substrate-alexander:latest
    hostname: substrate-node
    volumes:
      - 'substrate-data:/data'
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --dev --rpc-port 9933 --rpc-external --ws-external --pruning=10000000

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: Dev
        NETWORK_TOKEN_SYMBOL: DOT
        NETWORK_TOKEN_DECIMALS: 0
        API_URL: http://127.0.0.1:8080/api/v1/
    ports:
      - '8080:80'
    depends_on:
      - harvester-api
      - explorer-api

volumes:
  db-data:
  substrate-data:
